/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShellImport } from './routes/_shell'
import { Route as ShellIndexImport } from './routes/_shell/index'
import { Route as ShellStationCountriesIndexImport } from './routes/_shell/stationCountries/index'
import { Route as ShellOpenLibraryIndexImport } from './routes/_shell/openLibrary/index'
import { Route as ShellEnergyChartsIndexImport } from './routes/_shell/energyCharts/index'
import { Route as ShellStationCountriesCountryImport } from './routes/_shell/stationCountries/$country'

// Create/Update Routes

const ShellRoute = ShellImport.update({
  id: '/_shell',
  getParentRoute: () => rootRoute,
} as any)

const ShellIndexRoute = ShellIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)

const ShellStationCountriesIndexRoute = ShellStationCountriesIndexImport.update(
  {
    id: '/stationCountries/',
    path: '/stationCountries/',
    getParentRoute: () => ShellRoute,
  } as any,
)

const ShellOpenLibraryIndexRoute = ShellOpenLibraryIndexImport.update({
  id: '/openLibrary/',
  path: '/openLibrary/',
  getParentRoute: () => ShellRoute,
} as any)

const ShellEnergyChartsIndexRoute = ShellEnergyChartsIndexImport.update({
  id: '/energyCharts/',
  path: '/energyCharts/',
  getParentRoute: () => ShellRoute,
} as any)

const ShellStationCountriesCountryRoute =
  ShellStationCountriesCountryImport.update({
    id: '/stationCountries/$country',
    path: '/stationCountries/$country',
    getParentRoute: () => ShellRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ShellImport
      parentRoute: typeof rootRoute
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexImport
      parentRoute: typeof ShellImport
    }
    '/_shell/stationCountries/$country': {
      id: '/_shell/stationCountries/$country'
      path: '/stationCountries/$country'
      fullPath: '/stationCountries/$country'
      preLoaderRoute: typeof ShellStationCountriesCountryImport
      parentRoute: typeof ShellImport
    }
    '/_shell/energyCharts/': {
      id: '/_shell/energyCharts/'
      path: '/energyCharts'
      fullPath: '/energyCharts'
      preLoaderRoute: typeof ShellEnergyChartsIndexImport
      parentRoute: typeof ShellImport
    }
    '/_shell/openLibrary/': {
      id: '/_shell/openLibrary/'
      path: '/openLibrary'
      fullPath: '/openLibrary'
      preLoaderRoute: typeof ShellOpenLibraryIndexImport
      parentRoute: typeof ShellImport
    }
    '/_shell/stationCountries/': {
      id: '/_shell/stationCountries/'
      path: '/stationCountries'
      fullPath: '/stationCountries'
      preLoaderRoute: typeof ShellStationCountriesIndexImport
      parentRoute: typeof ShellImport
    }
  }
}

// Create and export the route tree

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellStationCountriesCountryRoute: typeof ShellStationCountriesCountryRoute
  ShellEnergyChartsIndexRoute: typeof ShellEnergyChartsIndexRoute
  ShellOpenLibraryIndexRoute: typeof ShellOpenLibraryIndexRoute
  ShellStationCountriesIndexRoute: typeof ShellStationCountriesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellStationCountriesCountryRoute: ShellStationCountriesCountryRoute,
  ShellEnergyChartsIndexRoute: ShellEnergyChartsIndexRoute,
  ShellOpenLibraryIndexRoute: ShellOpenLibraryIndexRoute,
  ShellStationCountriesIndexRoute: ShellStationCountriesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ShellRouteWithChildren
  '/': typeof ShellIndexRoute
  '/stationCountries/$country': typeof ShellStationCountriesCountryRoute
  '/energyCharts': typeof ShellEnergyChartsIndexRoute
  '/openLibrary': typeof ShellOpenLibraryIndexRoute
  '/stationCountries': typeof ShellStationCountriesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/stationCountries/$country': typeof ShellStationCountriesCountryRoute
  '/energyCharts': typeof ShellEnergyChartsIndexRoute
  '/openLibrary': typeof ShellOpenLibraryIndexRoute
  '/stationCountries': typeof ShellStationCountriesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/stationCountries/$country': typeof ShellStationCountriesCountryRoute
  '/_shell/energyCharts/': typeof ShellEnergyChartsIndexRoute
  '/_shell/openLibrary/': typeof ShellOpenLibraryIndexRoute
  '/_shell/stationCountries/': typeof ShellStationCountriesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/stationCountries/$country'
    | '/energyCharts'
    | '/openLibrary'
    | '/stationCountries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stationCountries/$country'
    | '/energyCharts'
    | '/openLibrary'
    | '/stationCountries'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/stationCountries/$country'
    | '/_shell/energyCharts/'
    | '/_shell/openLibrary/'
    | '/_shell/stationCountries/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_shell"
      ]
    },
    "/_shell": {
      "filePath": "_shell.tsx",
      "children": [
        "/_shell/",
        "/_shell/stationCountries/$country",
        "/_shell/energyCharts/",
        "/_shell/openLibrary/",
        "/_shell/stationCountries/"
      ]
    },
    "/_shell/": {
      "filePath": "_shell/index.tsx",
      "parent": "/_shell"
    },
    "/_shell/stationCountries/$country": {
      "filePath": "_shell/stationCountries/$country.tsx",
      "parent": "/_shell"
    },
    "/_shell/energyCharts/": {
      "filePath": "_shell/energyCharts/index.tsx",
      "parent": "/_shell"
    },
    "/_shell/openLibrary/": {
      "filePath": "_shell/openLibrary/index.tsx",
      "parent": "/_shell"
    },
    "/_shell/stationCountries/": {
      "filePath": "_shell/stationCountries/index.tsx",
      "parent": "/_shell"
    }
  }
}
ROUTE_MANIFEST_END */
